Get http://localhost:3001/todos 

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
} 

###
DELETE http://localhost:3001/todo/delete/66c4fa6ae95d9d5dabbb8f96

###
PUT http://localhost:3001/todo/complete/66c4fa30e95d9d5dabbb8f93